models:
  - name: silver_airports
    description: Its a cleaned airports data
    data_tests:
      - dbt_expectations.expect_table_columns_to_contain_set:
          arguments:
            column_list: ["airport_ident", "airport_type"]
    columns:
      - name: airport_ident
        description: Its a unique identifier for airports
        data_tests:
          - unique
          - not_null
          - relationships:
              arguments:
                to: ref('silver_airport_comments')
                field: airport_ident
                config:
                  severity: warn
          - relationships:
              arguments:
                to: ref('silver_runways')
                field: airport_ident
                config:
                  severity: warn
          - dbt_expectations.expect_table_column_count_to_be_between:
              arguments:
                min_value: 1
                max_value: 100

      - name: airport_type
        description: '{{ doc("airports_types_docs") }}'
        data_tests:
          - accepted_values:
              arguments:
                values:
                  [
                    "heliport",
                    "small_airport",
                    "closed",
                    "seaplane_base",
                    "balloonport",
                    "medium_airport",
                    "large_airport",
                  ]
          - dbt_expectations.expect_column_values_to_be_in_set:
              arguments:
                value_set:
                  [
                    "heliport",
                    "small_airport",
                    "closed",
                    "seaplane_base",
                    "balloonport",
                    "medium_airport",
                    "large_airport",
                  ]

  - name: silver_airport_comments
    description: Its a cleaned airport comments data
    columns:
      - name: comment_id
        data_tests:
          - unique
          - not_null

  - name: silver_runways
    description: Its a cleaned runways data
    columns:
      - name: runway_id
        data_tests:
          - unique
          - not_null
      - name: runway_closed
        data_tests:
          - accepted_values:
              arguments:
                values: ["1", "0"]
